Dollar = 50
Leverage = 1
TIME_PERIOD = "15m"
LIMIT = "1500"
TIME_SLEEP = 2
Dollars = Dollar * Leverage
above_or_below_wick = 0.1
trailing_order_check = 0.3
trailing_order_increase = 0.1
max_take_profit_limit = 20
